version: "3.7"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-6.5.0}
    hostname: "{{.Node.Hostname}}-elasticsearch"
    environment:
      - discovery.zen.ping.unicast.hosts=elasticsearch
      - discovery.zen.minimum_master_nodes=3
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
      - xpack.security.enabled=true
      - xpack.monitoring.collection.enabled=true
      - xpack.license.self_generated.type=trial
      - cluster.name=DevOps
      - node.name={{.Node.Hostname}}-elasticsearch
      - network.host=0.0.0.0
    networks:
      - elastic
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    deploy:
      replicas: 1



  # logstash:
  #   image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION:-6.5.0}
  #   hostname: "{{.Node.Hostname}}-logstash"
  #   environment:
  #     - XPACK_MONITORING_ELASTICSEARCH_URL=http://elasticsearch:9200
  #     - XPACK_MONITORING_ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
  #     - XPACK_MONITORING_ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
  #   networks:
  #     - elastic
  #   deploy:
  #     replicas: 2
  #     labels:
  #       - "traefik.port=5044"
  #       - "traefik.frontend.rule=Host:${DOMAIN};Path:/logstash"
  #       - "traefik.backend.loadbalancer.stickiness=true"
  #       - "traefik.backend=logstash"
  #       - "traefik.enable=true"
  #       - "traefik.docker.network=elastic"
  #   configs:
  #     - source: ls_config
  #       target: /usr/share/logstash/pipeline/logstash.conf



  # kibana:
  #   image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION:-6.5.0}
  #   hostname: "{{.Node.Hostname}}-kibana"
  #   environment:
  #     - ELASTICSEARCH_URL=http://elasticsearch:9200
  #     - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
  #     - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
  #     - SERVER_NAME="{{.Node.Hostname}}-kibana"
  #   networks:
  #     - elastic
  #   volumes:
  #     - kibana:/usr/share/kibana/data
  #   deploy:
  #     replicas: 2
  #     labels:
  #       - "traefik.port=5601"
  #       - "traefik.frontend.rule=Host:${DOMAIN}"
  #       - "traefik.backend.loadbalancer.stickiness=true"
  #       - "traefik.backend=kibana"
  #       - "traefik.enable=true"
  #       - "traefik.docker.network=elastic"



  proxy:
    image: traefik:v2.2
    hostname: "{{.Node.Hostname}}-traefik"
    networks:
      - ${TRAEFIK_PUBLIC_NETWORK?Variable not set}
      - elastic
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      # Enable Docker in Traefik, so that it reads labels from Docker services
      - --providers.docker
      # Add a constraint to only use services with the label for this stack
      # from the env var TRAEFIK_TAG
      - --providers.docker.constraints=Label(`traefik.constraint-label-stack`, `${TRAEFIK_TAG?Variable not set}`)
      # Do not expose all Docker services, only the ones explicitly exposed
      - --providers.docker.exposedbydefault=false
      # Enable Docker Swarm mode
      - --providers.docker.swarmmode
      - --providers.docker.watch
      # Enable the access log, with HTTP requests
      - --accesslog
      # Enable the Traefik log, for configurations and errors
      - --log
      # Enable the Dashboard and API
      - --api
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        # Enable Traefik for this service, to make it available in the public network
        - traefik.enable=true
        # Use the traefik-public network (declared below)
        - traefik.docker.network=${TRAEFIK_PUBLIC_NETWORK?Variable not set}
        # Use the custom label "traefik.constraint-label=traefik-public"
        # This public Traefik will only use services with this label
        - traefik.constraint-label=${TRAEFIK_PUBLIC_TAG?Variable not set}
        # traefik-http set up only to use the middleware to redirect to https
        - traefik.http.middlewares.${STACK_NAME?Variable not set}-https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.${STACK_NAME?Variable not set}-https-redirect.redirectscheme.permanent=true
        # Handle host with and without "www" to redirect to only one of them
        # Uses environment variable DOMAIN
        # To disable www redirection remove the Host() you want to discard, here and
        # below for HTTPS
        - traefik.http.routers.${STACK_NAME?Variable not set}-proxy-http.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.${STACK_NAME?Variable not set}-proxy-http.entrypoints=http
        # traefik-https the actual router using HTTPS
        - traefik.http.routers.${STACK_NAME?Variable not set}-proxy-https.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.${STACK_NAME?Variable not set}-proxy-https.entrypoints=https
        - traefik.http.routers.${STACK_NAME?Variable not set}-proxy-https.tls=true
        # Use the "le" (Let's Encrypt) resolver created below
        - traefik.http.routers.${STACK_NAME?Variable not set}-proxy-https.tls.certresolver=le
        # Define the port inside of the Docker service to use
        - traefik.http.services.${STACK_NAME?Variable not set}-proxy.loadbalancer.server.port=80
        # Handle domain with and without "www" to redirect to only one
        # To disable www redirection remove the next line
        - traefik.http.middlewares.${STACK_NAME?Variable not set}-www-redirect.redirectregex.regex=^https?://(www.)?(${DOMAIN?Variable not set})/(.*)
        # Redirect a domain with www to non-www
        # To disable it remove the next line
        - traefik.http.middlewares.${STACK_NAME?Variable not set}-www-redirect.redirectregex.replacement=https://${DOMAIN?Variable not set}/$${3}
        # Redirect a domain without www to www
        # To enable it remove the previous line and uncomment the next
        # - traefik.http.middlewares.${STACK_NAME}-www-redirect.redirectregex.replacement=https://www.${DOMAIN}/$${3}
        # Middleware to redirect www, to disable it remove the next line 
        - traefik.http.routers.${STACK_NAME?Variable not set}-proxy-https.middlewares=${STACK_NAME?Variable not set}-www-redirect
        # Middleware to redirect www, and redirect HTTP to HTTPS
        # to disable www redirection remove the section: ${STACK_NAME?Variable not set}-www-redirect,
        - traefik.http.routers.${STACK_NAME?Variable not set}-proxy-http.middlewares=${STACK_NAME?Variable not set}-www-redirect,${STACK_NAME?Variable not set}-https-redirect


  # traefik:
  #   image: traefik:v1.7.8
  #   hostname: "{{.Node.Hostname}}-traefik"
    # command: 
      # - "--docker"
      # - "--docker.swarmmode"
      # - "--docker.domain=${DOMAIN}"
      # - "--docker.watch" 
      # - "--logLevel=DEBUG"
      # - "--docker.network=elastic"
      # - "--api"
    #   - "--entrypoints=Name:http Address::80"
    #   - "--defaultentrypoints=http"
    #   - "--docker.exposedbydefault=false"
    #   - "--accessLog"
    # networks:
      # - elastic
    # ports:
    #   - "80:80"
    #   - "443:443"
    #   - "8080:8080"
    # volumes:
    #   - type: bind
    #     source: /var/run/docker.sock
    #     target: /var/run/docker.sock
    # deploy:
    #   replicas: 1
    #   placement:
    #     constraints:
    #       - "node.role == manager"



networks:
    elastic:
      driver: ${DEFAULT_NETWORK_TYPE-overlay}
    traefik-public:
      external: true

volumes:
  elasticsearch:
  kibana:

configs:
  ls_config:
    file: $PWD/logstash.conf
