version: "3.7"

services:
  curator:
    image: registry.track.uz/curator:elasticdocker-${ELK_VERSION?latest}
    build:
      context: curator/.
    restart: unless-stopped
    volumes:
      - ./curator/curator.yml:/root/.curator/curator.yml:ro
      - ./curator/actions/:/actions/:ro
      - ./curator/crontab:/etc/crontab:ro
    networks:
      - elastic
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    deploy:
      placement:
        constraints:
          - node.labels.curator == true

networks:
  elastic:
    driver: ${DEFAULT_NETWORK_TYPE-overlay}
  traefik-public:
    external: true
